config/routes.rb
Rails.application.routes.draw do

  resources :cocktails, only: [:index, :show, :new, :create] do
    resources :doses, only: [:new, :create, :edit, :update]
  end
  resources :doses, only: [:edit, :update, :destroy]

  root "cocktails#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
    validates :name, presence: true, uniqueness: true
    has_many :doses, dependent: :destroy
    has_many :ingredients, through: :doses
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates_uniqueness_of :cocktail, scope: :ingredient
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
    validates :name, presence: true, uniqueness: true
        
    has_many :doses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @dose = Dose.new
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
     if @cocktail.save
      redirect_to new_cocktail_dose_path(@cocktail)
     else
      render :new
     end
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :find_dose, only: [:edit, :update, :destroy]

  def new
    @dose = Dose.new
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def create
    @dose = Dose.new(dose_params)
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @dose.update(dose_params)
     else
      render :edit  
     end
  end

  def destroy
  end

  private

  def dose_params
    params.require(:dose).permit(:amount, :volume, :description, :ingredient_id, :cocktail_id)
  end

  def find_dose
    @dose = Dose.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/create.html.erb
<h1>Cocktails#create</h1>
<p>Find me in app/views/cocktails/create.html.erb</p>

app/views/cocktails/index.html.erb
    <h1>Cocktails</h1>
<div class="cards-container">  
<%= select_tag 'ingredient', options_for_select(Ingredient.all.collect{ |x| x.name })  %>

    <div class="grid">
        <% @cocktails.each do |a| %>
        <div class="element">
            <h3 class="header"><%= link_to a.name, cocktail_path(a) %></h3>     
        </div>
        <% end %>
    </div>
</div>

<%= link_to "create a cocktail!", new_cocktail_path %>

app/views/cocktails/new.html.erb
NEW COCKTAIL

<%= form_for(@cocktail) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.submit %>
<% end %>

app/views/cocktails/show.html.erb
<h1><%= @cocktail.name %></h1>

<ul>
    <% @cocktail.doses.each do |dose| %>
        <li>
            <%= dose.ingredient.name%>--<%= dose.amount %>ml
        </li>
            <h3><%= dose.description %></h3>
       
    <% end %>
</ul>

<%= simple_form_for([@cocktail, @dose]) do |f| %>
  <%= f.input :ingredient_id, collection: Ingredient.all %>
  <%= f.input :amount %>
  <%= f.select :volume, %w(cl dl l )%>
  <%= f.submit %>

<% end %>

app/views/doses/create.html.erb
<h1>Doses#create</h1>
<p>Find me in app/views/doses/create.html.erb</p>

app/views/doses/destroy.html.erb
<h1>Doses#destroy</h1>
<p>Find me in app/views/doses/destroy.html.erb</p>

app/views/doses/new.html.erb
NEW DOSE


<%= simple_form_for([@cocktail, @dose]) do |f| %>
  <%= f.input :description %>

  <%= f.input :ingredient_id, collection: Ingredient.all %>
  <%= f.input :amount %>
  <%= f.select :volume, %w(cl dl l )%>
  <%= f.submit %>

<% end %>

app/views/doses/update.html.erb
<h1>Doses#update</h1>
<p>Find me in app/views/doses/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag     'application', 'https://fonts.googleapis.com/css?family=Raleway:500' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navbar"><%= link_to 'Mr Cocktail', cocktails_path %><%= link_to 'New Cocktail', new_cocktail_path %></div>
    <%= yield %>
    <div class="footer">Sven den Boer</div>
  </body>
</html>